### ISSUE TITLE
unimplemented instrinsic in `hyper` (`_mm256_lddqu_si256`)

### ISSUE THREAD

**Issue by y21** [rust-lang/rustc_codegen_cranelift#1408]
Noticed this in a project using reqwest, but it also seems to reproduce using just hyper and tokio:
```toml
# Cargo.toml
[package]
name = "repro"
version = "0.1.0"
edition = "2021"

[dependencies]
hyper = { version = "0.14.27", features = ["client", "http1", "tcp"] }
tokio = { version = "1.33.0", features = ["full"] }
```
```rs
// main.rs
#[tokio::main]
async fn main() {
    let client = hyper::Client::new();
    client
        .request(
            hyper::Request::builder()
                .uri("http://httpbin.org/get")
                .body(hyper::Body::empty())
                .unwrap(),
        )
        .await
        .unwrap();
}
```
```
trap at Instance { def: Item(DefId(2:14310 ~ core[53bd]::core_arch::x86::avx::_mm256_lddqu_si256)), args: [] } (_ZN4core9core_arch3x863avx18_mm256_lddqu_si25617h4bd75b5668ffeef1E): llvm.x86.avx.ldu.dq.256
``` 
Awesome project btw! It's great to see that this is available as a rustup component now
