### ISSUE TITLE
i128 abi incompatibility with cg_llvm

### ISSUE THREAD

**Issue by DrewRidley** [rust-lang/rustc_codegen_cranelift#1449]
Hi all,

I was informed a little over a week ago that it should be possible to mix ``LLVM`` and cranelift in the same rust target. I went about writing a game in bevy, and using ``opt = 3`` with LLVM for my dependencies. I used the following toml file to achieve this:
```
[profile.dev.package."*"]
codegen-backend = "llvm"

[profile.dev]
codegen-backend = "cranelift"
```

I then added bevy as a dependency, and ran the simple example provided. All was well and the examples listed on their website run as expected. However, as soon as a ``Plugin`` is written in a cranelift context, and added to the LLVM emitted bevy code, a segmentation fault occurs. I suspect it might have to do with calling conventions, but my knowledge about LLVM and Cranelift is limited so I won't be much help here.

Here is a minimal example that should illustrate the problem:
```
use bevy::prelude::*;

pub struct MyCraneliftPlugin;

impl Plugin for MyCraneliftPlugin {
    fn build(&self, app: &mut App) {
       app.add_systems(Update, || { debug!("Hello world!") });
    }
}

   fn main() {
    App::new()
        .add_plugins(MinimalPlugins)
        .add_plugins(MyCraneliftPlugin)
        .run();
}
```

Compiling the following exclusively with LLVM or exclusively with Cranelift works as expected. Mixing the backends with the config provided earlier causes a segfault. I tried to investigate where exactly the segmentation fault occurs with lldb but was largely unsuccessful as it was not clear which code emitted was from cranelift and which was llvm.

Any help would be much appreciated, and I apologize I could not be more help here.

**Comment by bjorn3** [comment]
I can reproduce the crash with the following Cargo.toml:

```toml
[package]
name = "crash_repro"
version = "0.1.0"
edition = "2021"

[dependencies]
bevy = "0.12.1"

[profile.dev.package."*"]
codegen-backend = "llvm"
opt-level = 3

[profile.dev]
codegen-backend = "cranelift"
```
