### ISSUE TITLE
cargo config.toml's rustflags not supporting `--cfg=web_sys_unstable_apis`

### ISSUE THREAD

**Issue by luxalpa** [rust-lang/rustc_codegen_cranelift#1486]
I'm trying to use web_sys. It works without cargo-clif. It also works if I set my environment variables to `RUSTFLAGS=--cfg=web_sys_unstable_apis`. But it doesn't seem to be able to pick it up from my `.cargo/config.toml` that's located in the project. I'm using Windows 11.

```toml
[build]
rustflags = ["--cfg=web_sys_unstable_apis", "-Z", "threads=8"]
```
