### ISSUE TITLE
cranelift fails to build Bevy 0.13.2 on macOS

### ISSUE THREAD

**Issue by janhohenheim** [rust-lang/rustc_codegen_cranelift#1504]
`cargo --version`: `cargo 1.81.0-nightly (b1feb75d0 2024-06-07)`

<details>
<summary>Cargo.toml</summary>

```toml
[package]
name = "cranelift-test"
version = "0.1.0"
edition = "2021"

[dependencies]
bevy = "0.13.2"
```

</details>
<details>
<summary>main.rs</summary>

```rust
fn main() {
    println!("Hello, world!");
}
```

</details>

<details>
<summary>~/.cargo/config.toml</summary>

```toml
[unstable]
codegen-backend = true

[profile.dev]
codegen-backend = "cranelift"
```

</details>

System:
<img width="392" alt="image" src="https://github.com/rust-lang/rustc_codegen_cranelift/assets/9047632/c3cd676a-77b5-4952-9f0a-a289d05c5cbf">

Running `cargo build` results in the following:
```ignore
error: error writing object file: section name `__cstring,cstring_literals` is too long

error: could not compile `objc2` (lib) due to 1 previous error
```
