### ISSUE TITLE
Running tests using Bevy 0.14.0 fails on Windows

### ISSUE THREAD

**Issue by janhohenheim** [rust-lang/rustc_codegen_cranelift#1508]
## Setup

<details>
<summary>
Cargo.toml
</summary>

```toml
[package]
name = "minimal_doctest_fail"
version = "0.1.0"
authors = ["Jan Hohenheim <jan@hohenheim.ch>"]
edition = "2021"

[dependencies]
bevy = { version = "0.14.0", features = ["dynamic_linking"] }

[profile.dev]
opt-level = 1

[profile.dev.package."*"]
opt-level = 3

```
</details>

<details>
<summary>
lib.rs
</summary>

```rust
/// ```
/// use bevy::prelude::*;
/// 
/// App::new().add_plugins(DefaultPlugins);
/// ```
pub struct Foo;
```
</details>

- Add the output of `rustc-clif --print target-libdir` to my `PATH` per https://github.com/rust-lang/rustc_codegen_cranelift/issues/1505 
- Run `cargo clif test --doc`

## Result

```
running 1 test
test src\lib.rs - Foo (line 1) ... FAILED

failures:

---- src\lib.rs - Foo (line 1) stdout ----
Test executable failed (exit code: 0xc000001d).

stderr:
thread 'main' panicked at C:\Users\conta\.cargo\registry\src\index.crates.io-6f17d22bba15001f\bevy_tasks-0.14.0\src\task_pool.rs:186:22:
Failed to spawn thread.: Os { code: 87, kind: InvalidInput, message: "The parameter is incorrect." }
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace



failures:
    src\lib.rs - Foo (line 1)

test result: FAILED. 0 passed; 1 failed; 0 ignored; 0 measured; 0 filtered out; finished in 1.28s

error: doctest failed, to rerun pass `--doc`
```

## Additional Notes

I don't know if the fact I'm using dynamic linking is relevant for this issue.

**Comment by janhohenheim** [comment]
Update: Managed to generate a smaller example that results in another error, but it pulls in another dependency:

<details>
<summary>
Cargo.toml
</summary>

```toml
[package]
name = "minimal_doctest_fail"
version = "0.1.0"
authors = ["Jan Hohenheim <jan@hohenheim.ch>"]
edition = "2021"

[dependencies]
# remove the `dynamic_linking` feature to fix the issue.
bevy = { version = "0.14.0", features = ["dynamic_linking"] }
avian3d = { git = "https://github.com/Jondolf/bevy_xpbd", branch = "avian"}

[profile.dev]
opt-level = 1

[profile.dev.package."*"]
opt-level = 3
```
</details>

<details>
<summary>
lib.rs
</summary>

```rust
/// ```
/// use bevy::prelude::*;
/// use avian3d::prelude::*;
/// 
/// App::new().add_plugins((MinimalPlugins, PhysicsPlugins::default()));
/// ```
```
</details>

This results in the following:
<details>
<summary>
Error message
</summary>

```
running 1 test
test src\lib.rs - Foo (line 1) ... FAILED

failures:

---- src\lib.rs - Foo (line 1) stdout ----
Test executable failed (exit code: 0xc000001d).

stderr:
thread 'main' panicked at D:\a\rustc_codegen_cranelift\rustc_codegen_cranelift\build\stdlib\library\std\src\sync\once.rs:217:20:
assertion failed: state_and_queue.addr() & STATE_MASK == RUNNING
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace



failures:
    src\lib.rs - Foo (line 1)

test result: FAILED. 0 passed; 1 failed; 0 ignored; 0 measured; 0 filtered out; finished in 3.70s

error: doctest failed, to rerun pass `--doc`
```
</details>

For context, Avian is one of the two major physics engines for Bevy.
